"""your message

Revision ID: 1f4ae3c17f72
Revises: f23eadc509e2
Create Date: 2025-07-09 00:47:35.810946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4ae3c17f72'
down_revision = 'f23eadc509e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_user_workout_assignment'), type_='unique')
        batch_op.create_unique_constraint('uix_user_workout_assignment', ['user_id', 'workout_id', 'is_active'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_workout_assignment', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_user_workout_assignment'), ['user_id', 'workout_id'])

    # ### end Alembic commands ###
