"""Add is_admin field to User model

Revision ID: 252cbef712bc
Revises: ecdd82d0250e
Create Date: 2025-07-05 00:45:20.881027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252cbef712bc'
down_revision = 'ecdd82d0250e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
