"""Add WorkoutSession and SetLog models

Revision ID: 2cad9861f396
Revises: d7180bf7f0a6
Create Date: 2025-07-03 22:27:59.310342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cad9861f396'
down_revision = 'd7180bf7f0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_session_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight_unit', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distance_unit', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('set_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_set_exercise_date'))
        batch_op.drop_index(batch_op.f('ix_set_logs_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_set_logs_session_id'))
        batch_op.drop_constraint(batch_op.f('uix_session_exercise_set'), type_='unique')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'workout_sessions', ['workout_session_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('time_duration')
        batch_op.drop_column('logged_at')
        batch_op.drop_column('rpe')
        batch_op.drop_column('session_id')
        batch_op.drop_column('completed')

    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_assignment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('perceived_exertion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_session_user_date'))
        batch_op.drop_index(batch_op.f('idx_session_workout_date'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_workout_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workout_assignments', ['workout_assignment_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('duration')
        batch_op.drop_column('workout_id')
        batch_op.drop_column('difficulty_rating')
        batch_op.drop_column('started_at')
        batch_op.drop_column('mood')
        batch_op.drop_column('calories_burned')

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('difficulty_rating', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('workout_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_workout_sessions_workout_id'), ['workout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_session_workout_date'), ['workout_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_session_user_date'), ['user_id', 'started_at'], unique=False)
        batch_op.drop_column('completed')
        batch_op.drop_column('perceived_exertion')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('session_date')
        batch_op.drop_column('workout_assignment_id')

    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('rpe', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('logged_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('time_duration', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workout_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uix_session_exercise_set'), ['session_id', 'exercise_id', 'set_number'])
        batch_op.create_index(batch_op.f('ix_set_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_logs_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_set_exercise_date'), ['exercise_id', 'logged_at'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('set_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('distance_unit')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('weight_unit')
        batch_op.drop_column('workout_session_id')

    # ### end Alembic commands ###
