"""your message

Revision ID: 33c82d6c25c0
Revises: 252cbef712bc
Create Date: 2025-07-09 00:27:20.974058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c82d6c25c0'
down_revision = '252cbef712bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_workout_assignment_active', ['user_id', 'id', 'is_active'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_workout_assignment_active', type_='unique')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
