"""Added workout assignment

Revision ID: 36a6744351d5
Revises: f4d952d42dc9
Create Date: 2025-07-02 23:31:54.167045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a6744351d5'
down_revision = 'f4d952d42dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
    #     # batch_op.add_column(sa.Column('assigned_date', sa.DateTime(), nullable=True))
    #     # batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))

    # with op.batch_alter_table('workouts', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###

    pass
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('workouts', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
    #     batch_op.drop_column('completion_date')
        # batch_op.drop_column('completed')
        # batch_op.drop_column('assigned_date')

    # ### end Alembic commands ###
    pass