"""Enhanced models with constraints, indexes and nutrition tracking

Revision ID: 51bdb547112b
Revises: c359d0d33de3
Create Date: 2025-06-29 18:37:07.835778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bdb547112b'
down_revision = 'c359d0d33de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('assignment')
    # op.drop_table('nutrition_goals')
    # op.drop_table('sessions')
    # op.drop_table('exercise_logs')
    # op.drop_table('workout_plans')
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('logged_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_set_exercise_date', ['exercise_id', 'logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_logs_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_logs_session_id'), ['session_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'workout_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        # batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calorie_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protein_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carbs_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fat_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('water_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_user_email_username', ['email', 'username'], unique=False)

    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.alter_column('assigned_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uix_user_workout'), type_='unique')
        batch_op.create_index('idx_assignment_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_assignment_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_assigned_by'), ['assigned_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_workout_id'), ['workout_id'], unique=False)
        batch_op.create_unique_constraint('uix_user_workout_assignment', ['user_id', 'workout_id'])
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        # batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
        # batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index('idx_session_user_date', ['user_id', 'started_at'], unique=False)
        batch_op.create_index('idx_session_workout_date', ['workout_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_workout_id'), ['workout_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('workouts', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_workout_sessions_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_started_at'))
        batch_op.drop_index('idx_session_workout_date')
        batch_op.drop_index('idx_session_user_date')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'])
        batch_op.drop_constraint('uix_user_workout_assignment', type_='unique')
        batch_op.drop_index(batch_op.f('ix_workout_assignments_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_workout_assignments_assigned_by'))
        batch_op.drop_index('idx_assignment_user_status')
        batch_op.drop_index('idx_assignment_dates')
        batch_op.create_unique_constraint(batch_op.f('uix_user_workout'), ['user_id', 'workout_id'])
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('assigned_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_email_username')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('water_goal')
        batch_op.drop_column('fat_goal')
        batch_op.drop_column('carbs_goal')
        batch_op.drop_column('protein_goal')
        batch_op.drop_column('calorie_goal')

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_sessions', ['session_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_set_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_set_logs_exercise_id'))
        batch_op.drop_index('idx_set_exercise_date')
        batch_op.alter_column('logged_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_table('workout_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('exercises', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('mood', sa.VARCHAR(length=50), nullable=True),
    sa.Column('energy_level', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('daily_calories', sa.INTEGER(), nullable=True),
    sa.Column('protein_grams', sa.INTEGER(), nullable=True),
    sa.Column('carbs_grams', sa.INTEGER(), nullable=True),
    sa.Column('fat_grams', sa.INTEGER(), nullable=True),
    sa.Column('fiber_grams', sa.INTEGER(), nullable=True),
    sa.Column('water_ml', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
