"""Fix workout user relationship

Revision ID: 7165bc15a626
Revises: c7b7ff3e3195
Create Date: 2025-07-02 01:49:49.575737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7165bc15a626'
down_revision = 'c7b7ff3e3195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_email_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_email_username'), ['email', 'username'], unique=False)

    # ### end Alembic commands ###
