"""Fix ambiguous foreign keys in relationships

Revision ID: 8cb3b0b05229
Revises: 36a6744351d5
Create Date: 2025-07-02 23:55:00.424082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb3b0b05229'
down_revision = '36a6744351d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_assignments_user_id'))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('workouts', schema=None) as batch_op:
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('workouts', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_workout_assignments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
