"""Add JWT authentication and token blacklist

Revision ID: aad7edf491a7
Revises: 51bdb547112b
Create Date: 2025-06-30 23:48:45.532435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad7edf491a7'
down_revision = '51bdb547112b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # with op.batch_alter_table('set_logs', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key(None, 'workout_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        # batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('workouts', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'])
        batch_op.create_foreign_key(None, 'workouts', ['workout_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workout_sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'])

    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
