"""Create fitness tracking core models

Revision ID: c359d0d33de3
Revises: 
Create Date: 2025-06-29 18:11:51.175647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c359d0d33de3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     #batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
    #     #batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
    #     batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('distance')
        batch_op.drop_column('date')
        batch_op.drop_column('notes')
        batch_op.drop_column('calories_burned')
        batch_op.drop_column('workout_type')
        batch_op.drop_column('duration')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('workout_type', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('calories_burned', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('image_url')
        batch_op.drop_column('is_public')
        batch_op.drop_column('created_by')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('title')

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_column('profile_image')
    #     batch_op.drop_column('last_login')
    #     batch_op.drop_column('name')

    # ### end Alembic commands ###
