"""Fix ambiguous foreign keys in relationships

Revision ID: d1f2c24e7133
Revises: 8cb3b0b05229
Create Date: 2025-07-03 00:04:49.212766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f2c24e7133'
down_revision = '8cb3b0b05229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('workouts', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###

    pass
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('workouts', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
    pass
    # ### end Alembic commands ###
