"""Added workout assignment

Revision ID: d7180bf7f0a6
Revises: d1f2c24e7133
Create Date: 2025-07-03 00:31:53.598688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7180bf7f0a6'
down_revision = 'd1f2c24e7133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duration')

    # with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
