"""initial

Revision ID: ecdd82d0250e
Revises: 
Create Date: 2025-07-04 00:34:27.071799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdd82d0250e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('STRENGTH', 'CARDIO', 'FLEXIBILITY', 'BALANCE', name='exercisetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_reps', sa.Integer(), nullable=True),
    sa.Column('default_sets', sa.Integer(), nullable=True),
    sa.Column('target_muscles', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('calorie_goal', sa.Integer(), nullable=True),
    sa.Column('protein_goal', sa.Integer(), nullable=True),
    sa.Column('carbs_goal', sa.Integer(), nullable=True),
    sa.Column('fat_goal', sa.Integer(), nullable=True),
    sa.Column('water_goal', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('protein_grams', sa.Integer(), nullable=True),
    sa.Column('carbs_grams', sa.Integer(), nullable=True),
    sa.Column('fat_grams', sa.Integer(), nullable=True),
    sa.Column('fiber_grams', sa.Integer(), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('total_fiber', sa.Float(), nullable=True),
    sa.Column('total_sugar', sa.Float(), nullable=True),
    sa.Column('total_sodium', sa.Float(), nullable=True),
    sa.Column('total_water', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_user_date_nutrition')
    )
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.create_index('idx_nutrition_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_logs_user_id'), ['user_id'], unique=False)

    op.create_table('nutrition_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Integer(), nullable=True),
    sa.Column('tdee', sa.Integer(), nullable=True),
    sa.Column('weight_goal', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('fitness_goal', sa.String(length=20), nullable=True),
    sa.Column('calorie_goal', sa.Integer(), nullable=True),
    sa.Column('protein_goal', sa.Integer(), nullable=True),
    sa.Column('carbs_goal', sa.Integer(), nullable=True),
    sa.Column('fat_goal', sa.Integer(), nullable=True),
    sa.Column('fiber_goal', sa.Integer(), nullable=True),
    sa.Column('water_goal', sa.Integer(), nullable=True),
    sa.Column('dietary_restrictions', sa.String(length=255), nullable=True),
    sa.Column('allergies', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrition_log_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('time_consumed', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nutrition_log_id'], ['nutrition_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index('idx_meal_type_time', ['meal_type', 'time_consumed'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_nutrition_log_id'), ['nutrition_log_id'], unique=False)

    op.create_table('workout_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workout_id', name='uix_user_workout_assignment')
    )
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_assignment_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_assignment_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_assigned_by'), ['assigned_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_assignments_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_sets', sa.Integer(), nullable=True),
    sa.Column('custom_reps', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('exercises', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_assignment_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_workout_session_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_assignment_id'], ['workout_assignments.id'], name='fk_workout_session_assignment', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('distance_unit', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_set_log_exercise', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], name='fk_set_log_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_logs')
    op.drop_table('workout_sessions')
    op.drop_table('workout_plans')
    op.drop_table('workout_exercises')
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_assignments_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_workout_assignments_assigned_by'))
        batch_op.drop_index('idx_assignment_user_status')
        batch_op.drop_index('idx_assignment_dates')

    op.drop_table('workout_assignments')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_nutrition_log_id'))
        batch_op.drop_index(batch_op.f('ix_meal_logs_meal_type'))
        batch_op.drop_index('idx_meal_type_time')

    op.drop_table('meal_logs')
    op.drop_table('exercise_logs')
    op.drop_table('workouts')
    op.drop_table('sessions')
    with op.batch_alter_table('nutrition_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_profiles_user_id'))

    op.drop_table('nutrition_profiles')
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_logs_user_id'))
        batch_op.drop_index('idx_nutrition_user_date')

    op.drop_table('nutrition_logs')
    op.drop_table('nutrition_goals')
    op.drop_table('assignments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_table('exercises')
    # ### end Alembic commands ###
