"""your message

Revision ID: f23eadc509e2
Revises: 33c82d6c25c0
Create Date: 2025-07-09 00:32:56.615386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23eadc509e2'
down_revision = '33c82d6c25c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_assignments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
