"""Fix workout user relationship

Revision ID: f4d952d42dc9
Revises: 8abe38f38f40
Create Date: 2025-07-02 02:21:46.092841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d952d42dc9'
down_revision = '8abe38f38f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', sa.String(length=50), nullable=True))
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workout_type')

    # ### end Alembic commands ###
